# Pour lancer le playbook ansible-playbook -i list_serv_Linux_faille -l groupe1 ==> 21 sudo.yml
# Il y a 21 groupes
- name: Recupération version sudo

  hosts: all

  remote_user: root

  tasks:

  - name: Recup infos redhat/oracleLinux/Suse
    shell: 'rpm -qa | grep ^sudo'
    when: (ansible_facts['os_family'] == "RedHat") or (ansible_facts['os_family'] == "Suse")
    register: sudo_ver_rhel

  - name: Recup infos debian
    shell: "dpkg -l | grep sudo | awk '{print $3}'"
    when: ansible_facts['distribution'] == "Debian"
    register: sudo_ver_deb

  #- name: Affichage infos
    #debug:
     # msg: "{{ inventory_hostname }};{{ sudo_ver_deb.stdout }}"
    #when: ansible_facts['distribution'] == "Debian"

  #- name: Affichage infos
    #debug:
     # msg: "{{ inventory_hostname }};{{ sudo_ver_rhel.stdout }}"
    #when: (ansible_facts['os_family'] == "RedHat") or (ansible_facts['os_family'] == "Suse")

  - name: Infos dans un csv
    lineinfile:
      path: /home/adm-kaldana/ansible_sudo/inventory_vuln_sudo.csv
      line: "{{ inventory_hostname }};{{ ansible_os_family }};{{ ansible_distribution }} {{ ansible_distribution_version }};{{sudo_ver_rhel.stdout }}"
      state: present
    when: (ansible_facts['os_family'] == "RedHat") or (ansible_facts['os_family'] == "Suse")
    delegate_to: localhost

  - name: Infos dans un csv
    lineinfile:
      path: /home/adm-kaldana/ansible_sudo/inventory_vuln_sudo.csv
      line: "{{ inventory_hostname }};{{ ansible_os_family }};{{ ansible_distribution }} {{ ansible_distribution_version }};{{sudo_ver_deb.stdout }}"
      state: present
    when: ansible_facts['distribution'] == "Debian"
    delegate_to: localhost
