- name: Recupération version sudo

  hosts: all

  remote_user: root

  tasks:
  - name: Gather the package facts
    package_facts:
      manager: auto

  - name: Print Package facts
    debug:
      var: ansible_facts.packages 

  - name: Check if sudo is installed
    debug:
      msg: "{{ ansible_facts.packages['sudo'][0]['version'] }}{{ ansible_facts.packages['sudo'][0]['release'] }}{{ ansible_facts.packages['sudo'][0]['arch'] }}"
    when: "'sudo' in ansible_facts.packages"
